import NewProductImg from "../../../Images/newProduct.jpeg";
import FeaturedProductImg from "../../../Images/featuredProduct.jpeg";
import HotProductImg from "../../../Images/hotProduct.jpeg";

export type productsDataType = {
    name: string,
    price: number,
    category: string,
    productImage: string,
    feature: string,
    star: number,
    shippingCost: string,
    quantityAvailable: number,
    count: number,
    reviews: string,
    description: string,
    returnPolicy: string,
    tax: string,
    _id: string,
}

export const toBeAdded = {
    "star": 3.5,
    "shippingTime": "",
    "seller": "",
    "reviews": "",
    "description": "",
    "returnPolicy": "",
}

export const productsData = [
    {
        "name": "Royal Bond",
        "price": 25,
        "category": "Bonds",
        "productImage": NewProductImg,
        "feature": "New Product",
        "star": 3.5,
        "shippingCost": "49",
        "quantityAvailable": 7,
        "reviews": "This is a review for Royal Bond",
        "description": "This is a description for Royal Bond",
        "returnPolicy": "This is a returnPolicy for Royal Bond",
        "tax": "0.5",
        "_id": "64ef231c2802e12e9c049cae",
    },
    {
        "name": "Soma Paint - Exclusive",
        "price": 73,
        "category": "General Paint",
        "productImage": FeaturedProductImg,
        "feature": "Featured Product",
        "star": 4.5,
        "shippingCost": "4",
        "quantityAvailable": 13,
        "reviews": "This is a review for Soma Paint - Exclusive",
        "description": "This is a description for Soma Paint - Exclusive",
        "returnPolicy": "This is a returnPolicy for Soma Paint - Exclusive",
        "tax": "1",
        "_id": "64ef239a2802e12e9c049cb0",
    },
    {
        "name": "Granny Paint - Explosive",
        "price": 21,
        "category": "General Paint",
        "productImage": FeaturedProductImg,
        "feature": "Featured Product",
        "star": 4.8,
        "shippingCost": "4",
        "quantityAvailable": 13,
        "reviews": "This is a review for Granny Paint - Explosive",
        "description": "This is a description for Granny Paint - Explosive",
        "returnPolicy": "This is a returnPolicy for Granny Paint - Explosive",
        "tax": "1",
        "_id": "64ef249e2802e12a9c042cb0",
    },
    {
        "name": "Soft gelly fillas - Elastic",
        "price": 105,
        "category": "P.O.P Fillas",
        "productImage": HotProductImg,
        "feature": "Hot Product",
        "star": 4.7,
        "shippingCost": "43",
        "quantityAvailable": 3,
        "reviews": "This is a review for Soft gelly fillas - Elastic",
        "description": "This is a description for Soft gelly fillas - Elastic",
        "returnPolicy": "This is a returnPolicy for Soft gelly fillas - Elastic",
        "tax": "3",
        "_id": "64ef24412802e12e9c049cb2",
    },
    {
        "name": "Roll and Jug Binding Wires - Silver",
        "price": 33,
        "category": "Binding Wires",
        "productImage": NewProductImg,
        "feature": "New Product",
        "star": 4.8,
        "shippingCost": "13",
        "quantityAvailable": 5,
        "reviews": "This is a review for Roll and Jug Binding Wires - Silver",
        "description": "This is a description for Roll and Jug Binding Wires - Silver",
        "returnPolicy": "This is a returnPolicy for Roll and Jug Binding Wires - Silver",
        "tax": "8",
        "_id": "64ef25092802e12e9c049cb4",
    },
    {
        "name": "Top  Universal Painted paints",
        "price": 45000,
        "category": "Screeding Paint",
        "productImage": HotProductImg,
        "feature": "Hot Product",
        "star": 4.4,
        "shippingCost": "1700",
        "quantityAvailable": 18,
        "reviews": "This is a review for Top  Universal Painted paints",
        "description": "This is a description for Top  Universal Painted paints",
        "returnPolicy": "This is a returnPolicy for Top  Universal Painted paints",
        "tax": "500",
        "_id": "64fa961e8ab96b615763c357",
    },
    {
        "name": "Best P.O.P Plaster in town",
        "price": 3490,
        "category": "P.O.P Plaster",
        "productImage": NewProductImg,
        "feature": "New Product",
        "star": 3.5,
        "shippingCost": "1500",
        "quantityAvailable": 200,
        "reviews": "This is a review for Best P.O.P Plaster in town",
        "description": "This is a description for Best P.O.P Plaster in town",
        "returnPolicy": "This is a returnPolicy for Best P.O.P Plaster in town",
        "tax": "132",
        "_id": "64fae8be20a22bd6b4049dab",
    },
    {
        "name": "Sola Concrete nails that lasts for as long as you want it to with good shape and teeth as always",
        "price": 77000,
        "category": "Concrete Nails",
        "productImage": HotProductImg,
        "feature": "Hot Product",
        "star": 3.9,
        "shippingCost": "23000",
        "quantityAvailable": 32,
        "reviews": "This is a review for Sola Concrete nails that lasts for as long as you want it to with good shape and teeth as always",
        "description": "This is a description for Sola Concrete nails that lasts for as long as you want it to with good shape and teeth as always",
        "returnPolicy": "This is a returnPolicy for Sola Concrete nails that lasts for as long as you want it to with good shape and teeth as always",
        "tax": "1200",
        "_id": "64faea8d20a22bd6b4049daf",
    }
]